const PAGE_DIVIDER_HEIGHT = 1;
const SIDEBAR_CARD_HEIGHT = 32;
const SIDEBAR_CARD_GAP = 8;
const SELECTION_OFFSET = SIDEBAR_CARD_HEIGHT / 2;
const MIN_SELECTION_PX = 8;

export {
    MIN_SELECTION_PX,
    PAGE_DIVIDER_HEIGHT,
    SELECTION_OFFSET,
    SIDEBAR_CARD_GAP,
    SIDEBAR_CARD_HEIGHT,
};
